#!/bin/bash

#SBATCH --job-name=determ_test
#SBATCH -o determ_test.out
#SBATCH -p nodes
#SBATCH -e determ_error.out
#SBATCH -t 12:00:00
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --ntasks-per-socket=4
#SBATCH --distribution=cyclic:cyclic

#-- debug
#
  set echo


#-- environment
#
#  source /usr/share/modules/init/csh
#module load Anaconda/35

mpiexec -n 8 python parallel_test1.py

#-- exit
#
  unset echo
