#!/bin/bash

#SBATCH --job-name=determ_test
#SBATCH -o determ_test.out
#SBATCH -p nodes
#SBATCH -e determ_error.out
#SBATCH -t 12:00:00
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=16
#SBATCH --ntasks-per-socket=8
#SBATCH --distribution=cyclic:cyclic

#-- debug
#
  set echo


#-- environment
#
#  source /usr/share/modules/init/csh
#module load Anaconda/35

mpiexec -n 32 python parallel_test1.py

#-- exit
#
  unset echo
